### ISSUE TITLE
undercover.el causes tests to fail in emacs 24.4 and 24.5

### ISSUE THREAD

**Issue by bmag** [sviridov/undercover.el#12]
This build failed on Travis CI: https://travis-ci.org/bmag/emacs-purpose/builds/75722992
This build succeeded: https://travis-ci.org/bmag/emacs-purpose/builds/75723525
The only difference is disabling/enabling undercover, as can be seen in the diff between the two commits: https://github.com/bmag/emacs-purpose/commit/6ed404cdfd30d358af683c9e61f523ccf5a58a9a

A few months ago I didn't have any issues running undercover.el with emacs 24.4 and 24.5, as can be seen in the [build history](https://travis-ci.org/bmag/emacs-purpose/builds) and the [coverage history](https://coveralls.io/github/bmag/emacs-purpose).

Do you have any idea what could be the problem?

**Comment by sviridov** [comment]
@bmag I will investigate this asap.

**Comment by bmag** [comment]
thanks, I appreciate it

**Comment by sviridov** [comment]
@bmag As I mention in README, `undercover.el` is heavily based on `edebug` and can have some issues with macros coverage. And it is our case.

`define-purpose-compatible-advice` is a reason. It's `declare`  `debug` statement is incorrect. `t` means "All arguments are instrumented for evaluation". And for example here:

```lisp
(define-purpose-compatible-advice 'compilation-next-error-function
    :around purpose--fix-compilation-next-error
    (&rest args)
    "Integrate Purpose and `compilation-next-error-function'.
Advice that prevents `compilation-next-error-function' from hiding the
compilation buffer.  This is done by ensuring that the buffer is
dedicated for the duration of the function.
This function should be advised around
`compilation-next-error-function'."
  ;; new style advice
  ((let* ((compilation-window (get-buffer-window (marker-buffer (point-marker))))
          (old-window-dedicated-p (window-dedicated-p compilation-window)))
     (set-window-dedicated-p compilation-window t)
     (unwind-protect
         (apply oldfun args)
       (set-window-dedicated-p compilation-window old-window-dedicated-p))))

  ;; old style advice
  ((let* ((compilation-window (get-buffer-window (marker-buffer (point-marker))))
          (old-window-dedicated-p (window-dedicated-p compilation-window)))
     (set-window-dedicated-p compilation-window t)
     (unwind-protect
         ad-do-it
       (set-window-dedicated-p compilation-window old-window-dedicated-p)))))
```

not all arguments could be instrumented **as is** (because thay can't be evaluated as is). Please, change edebug declaration and let me know if it works for you.

Few notes:
- You can check that everything runs ok if `debug` is `0` or `(sexp sexp sexp sexp sexp sexp sexp)` (tested with emacs 24.4).

- You can emulate `undercover.el` work with `TRAVIS=true make test` (it will not actually submit any data). Just to ensure that `edebug` works fine.

- I did some improvments to `undercover.el` few days ago. Now, if something like that happends you will see message below  and `undercover.el` will fallback to simple file load without instrumenting.
  
   ```
    UNDERCOVER: error while covering /tmp/emacs-purpose/window-purpose-fixes.el
   ```

**Comment by sviridov** [comment]
@bmag ping :)

**Comment by bmag** [comment]
> You can check that everything runs ok if debug is 0 or (sexp sexp sexp sexp sexp sexp sexp) (tested with emacs 24.4).

I have removed all debug declarations from my code, just to be sure, and everything seems to run ok. Tested with 24.4 and 24.5 locally with TRAVIS=true.

>  if something like that happends you will see message below and undercover.el will fallback to simple file load without instrumenting.

> ```
> UNDERCOVER: error while covering /tmp/emacs-purpose/window-purpose-fixes.el
> ```

Indeed, I see this message when adding `(debug t)` back to `define-purpose-compatible-advice`.

It seems the problem is on my side, due to my lack of understanding how undercover and edebug work, so I'm closing this issue. Thank you for your help, I will be fixing my debug declarations now.
