### ISSUE TITLE
Error while covering cl-defstruct with slots and no default-value

### ISSUE THREAD

**Issue by DamienCassou** [sviridov/undercover.el#29]
I just got that for my [new project](https://github.com/DamienCassou/klassified.el):

```
UNDERCOVER: error while covering /home/cassou/.emacs.d/packages/klassified/klassified.el
UNDERCOVER: please open a new issue at https://github.com/sviridov/undercover.el/issues
```

**Comment by DamienCassou** [comment]
it seems to fail if I have this in the code:

```emacs
(cl-defstruct klassified-class
  (superclass-ref))
```

and it works again if I write this instead

```
(cl-defstruct klassified-class
  superclass-ref)
```

**Comment by sviridov** [comment]
@DamienCassou, it happens because `edebug` specification for `cl-defstruct` doesn't support such version of `cl-defstruct`. 

Just call `(get-edebug-spec 'cl-defstruct)` to see it. Result for my version of Emacs is:

```
(&define
 [&or symbolp
      (gate symbolp &rest
            (&or
             [":conc-name" symbolp]
             [":constructor" symbolp &optional cl-lambda-list]
             [":copier" symbolp]
             [":predicate" symbolp]
             [":include" symbolp &rest sexp]))]
 [&optional stringp]
 &rest &or symbolp
 (symbolp def-form &optional ":read-only" sexp))
```

First argument should either symbol or list that at least contains `gate` (no idea what it is) and symbol.

**Comment by DamienCassou** [comment]
Thank you for your answer.
