### ISSUE TITLE
Support for codecov

### ISSUE THREAD

**Issue by AdrieanKhisbe** [sviridov/undercover.el#34]
It would be cool if it was possible to send report to the [codecov](https://codecov.io) CI service as an alternative to coveralls.

I saw that logic foresaw need of different reports:
https://github.com/sviridov/undercover.el/blob/master/undercover.el#L418

I'll be glad to give a hand in the implementaton :)

**Comment by sviridov** [comment]
Hi @AdrieanKhisbe,

I'm on holidays right now, will be back on the next week.
But I will not have time to do it by myself, but I can definitely provide information on how it can be implemented (with links to the source code). Would you like to implement this feature? If yes, I will provide all required information on the next week.

**Comment by AdrieanKhisbe** [comment]
Hey @sviridov !
Thanks for the quick answer though in holidays :)
I like to implement the feature and then make it as an option on [cask-package-toolset.el](https://github.com/AdrieanKhisbe/cask-package-toolset.el).

But there is no hurry, enjoy your vacation 😃

**Comment by sviridov** [comment]
Hey @AdrieanKhisbe!

So, in order to add new report type support, you will need to:

1. Add `:report-type` parameter support. It can be done [here](https://github.com/sviridov/undercover.el/blob/master/undercover.el#L444). For other parameters, I used variables with a default value (which in our case should be `'coveralls`) in order to store parameter value.
2. Use this parameter [here](https://github.com/sviridov/undercover.el/blob/master/undercover.el#L238) instead of `'coveralls`.
3. Then [here](https://github.com/sviridov/undercover.el/blob/master/undercover.el#L424) you can define handler for this report type. `undercover--coveralls-report` is the best place to look for more information.
4. I'm not sure what data is required for `codecov` and in what format, but feel free to rename and reuse functions from `coveralls` report.

**Comment by gonewest818** [comment]
Just a friendly observation that [Codecov supports the Coveralls report format](https://docs.codecov.io/v4.3.6/reference#section-acceptable-report-formats) too.  Which means a simpler way to get this feature would be to implement `undercover--send-codecov-report` (sends the coveralls data to codecov's API endpoint), and a `:destination` parameter to indicate where the report goes (either 'coveralls or 'codecov). Down the road you still may need to support other `:report-types` but it just so happens you don't need a new report type for codecov.

**Comment by sviridov** [comment]
Awesome, thanks for the advice @gonewest818!
Maybe it's still a good idea to use new `:report-type`, but re-use `coveralls` related code. Just in case if we will want to change `codecov` report related code later.

**Comment by AdrieanKhisbe** [comment]
Thanks for the advice @gonewest818 !
It's a bit in stand by since I didn't get answer from @codecov, and didn't code much emacs-lisp these last week.
But based on what you say gonewest, I'll just have to use the good endpoint

**Comment by xendk** [comment]
In case anyone else would like to try out Codecov before this issue is closed, here's a working example:

Loading undercov: 
https://github.com/xendk/indentinator/blob/e9bfacd16ee03c956008f4ed1cb2e0cec50046c2/features/support/env.el#L24

And uploading using the standard upload tool:
https://github.com/xendk/indentinator/blob/e9bfacd16ee03c956008f4ed1cb2e0cec50046c2/.travis.yml#L42

Not much too it other than specifying an output file and telling undercover to not upload, and pointing the bash script at the right file. Builtin support would be extra nice though.

**Comment by gonewest818** [comment]
I did basically the same in this project: https://github.com/gonewest818/adafruit-wisdom.el/commit/c0fdfcbbbc49927e0c93656f6d4a877cca774224

Agree, it would be nice to have this integrated though.

**Comment by sviridov** [comment]
Hi @xendk, @gonewest818 thanks for the examples!

> Agree, it would be nice to have this integrated though.

I agree with you, but unfortunately, I don't have time nor motivation to actively work on this project. I guess I will need to find another maintainer for it.

P.S. Obviously, pull requests are welcome.

**Comment by xendk** [comment]
A quick way to implement Codecov support would be just calling `sh -c "curl -s https://codecov.io/bash | bash -s - -f coverage.json"` from Emacs, and let their script figure out the details.

But taking a step back, should undercover really implement uploading of coverage? Coveralls seems like the odd case, implementing the uploading directly in the coverage gathering (Gem or whatever) while Codecov, CodeClimate and ScrutinizerCI all simply collects and uploads coverage files generated by the tests, which is run as a separate step by the CI.

So, considering the lack of manpower, I'd suggest implementing Codecov support as a general `:service` option that simply sets `:send-report` to `nil` and `:report-file` to a name that's auto-discovered by the Codecov bash script (`coverage-final.json` looks like a good candidate), and mention adding the Codecov bash script to the `.travis.yml` file. Down the line that could be extended to other services, possibly implementing other report formats.

**Comment by gonewest818** [comment]
In fact I’m pretty sure you can curl report data into coveralls as well... pretty sure that’s how it works with “cloverage”, the Clojure code coverage tool.  I’d say it’s fine to separate the uploading from the instrumenting, and perhaps even the coveralls uploader code can be dropped, if I’m recalling correctly about coveralls.

I personally like to run coverage reports locally when there is some kind of ascii or html report that can be read locally. So the built-in uploader ends up being something I toggle off or disable except in CI.
