### ISSUE TITLE
error while covering

### ISSUE THREAD

**Issue by yyoncho** [sviridov/undercover.el#40]
I am trying to setup undercover on my project and I am having the following error in travis. 

> UNDERCOVER: error while covering /home/travis/build/yyoncho/dap-mode/dap-mode.el
> UNDERCOVER: please open a new issue at https://github.com/sviridov/undercover.el/issues

can someone help be find out what is causing the issue: here it is link to the project: https://github.com/yyoncho/dap-mode

**Comment by sviridov** [comment]
Hi @yyoncho, 

Such error usually happens when `edebug` (which is actively used by `undercover.el`) is not able to cover some elisp code. The reason for that is differences between edebug [specification](http://www.gnu.org/software/emacs/manual/html_node/elisp/Specification-List.html) and actual code.

To see exactly which code coverage is failing do following:

- Run `M-: (require 'edebug)`;
- Run `M-x edebug-all-defs`;
- Run `M-x eval-buffer`;

It will show you which specification is failing. After a quick look (I haven't tested everything) it looks like the problem is located at `dap--debug-session` structure definition.

Error description: 

```
edebug-syntax-error: Invalid read syntax: "Failed matching", ("cl-defstruct" [&or symbolp (gate symbolp &rest (&or [":conc-name" symbolp] [":constructor" symbolp &optional cl-lambda-list] [":copier" symbolp] [":predicate" symbolp] [":include" symbolp &rest sexp]))] [&optional stringp] &rest &or symbolp (symbolp def-form &optional ":read-only" sexp))
```

**Comment by yyoncho** [comment]
Thanks for your help! The issue was caused by a difference in the handling of properties without initializer in 25.3 and 27
